### ISSUE TITLE
feat: 홈 화면 개발 (앨범 틀 포함)

### ISSUE THREAD

**Issue by Jeongh00** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_BE2#25]
# Title

- 홈 화면 개발

# TODO

- [x] 홈 화면 API 개발
- [x] 앨범 엔티티 구조 설계
- [x] 앨범 API 틀 설계

# etc

- nothing
