### ISSUE TITLE
feat: 앨범 공유하기 기능

### ISSUE THREAD

**Issue by Jeongh00** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_BE2#63]
# Title

- 앨범 공유하기 기능

# TODO

- [x] 공유하기 링크 api
- [x] A의 정보를 알아오는 GET API
- [x] B에게 데이터를 저장시키는 POST API

# etc
